### ISSUE TITLE
Create Quest Instance

### ISSUE THREAD

**Issue by maxcurrent420** [maxcurrent420/BeastBreeder#56]
**What** - Create a Quest Instance: Instantiate a Quest object in the NPC class with appropriate details such as name, difficulty, description, rewards, and tasks.

**Why** - I want players to be able to go on quests in the game, as per the Project Roadmap.
@autopilot

**Comment by fjrdomingues** [comment]
Hi, @maxcurrent420 your autopilot.json file is missing a comma. It's popping up an error on my side. Sorry if I am being intrusive, just wanted to let you know. Cheers

**Comment by maxcurrent420** [comment]
> Hi, @maxcurrent420 your autopilot.json file is missing a comma. It's popping up an error on my side. Sorry if I am being intrusive, just wanted to let you know. Cheers

No worries, I think it should be fixed now- Thank you!

**Comment by fjrdomingues** [comment]
(it that I should not name here) was replying to the word "autopilot.json" but no longer- fixed! Thanks for the help.
